# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 6

version: "{build}"
build: off
deploy: off

branches:
    only:
      - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: "npm test"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
